[package]
name = "smelt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "smelt-cli"
path = "cli/main.rs"

[lib]
name = "smelt"
path = "engine/lib.rs"

[dependencies]
